#!/usr/bin/bash

ewwbar="eww --config $HOME/.config/eww/bar"

max_opacity="1"
min_opacity="0.5"

i3-msg -t subscribe -m '[ "window", "workspace" ]' |
    while IFS= read -r
    do
        opaque=$(printf "%.0f\n" $($ewwbar get bar-opacity))

        workspace_number=$(xprop -notype -root _NET_CURRENT_DESKTOP | cut -c 24-)
        window_count=$(i3-msg -t get_tree | jq "[.nodes[].nodes[]?.nodes[$workspace_number]? | select(.type == \"workspace\") | del(..?|.floating_nodes[]?) | ..? | select(.window?)] | length")

        if [ "$window_count" -eq 1 ] && [ "$opaque" -eq 0 ]; then
            (
                flock --exclusive --nonblock 200 || exit
                for i in $(seq $min_opacity 0.05 $max_opacity); do $ewwbar update bar-opacity=$i; done;
            ) 200>/tmp/polybarconfiglock
        elif [ "$window_count" -ne 1 ] && [ "$opaque" -eq 1 ]; then
            (
                flock --exclusive --nonblock 200 || exit
                for i in $(seq $max_opacity -0.05 $min_opacity); do $ewwbar update bar-opacity=$i; done;
            ) 200>/tmp/polybarconfiglock
        fi
    done &

pipepid=$!
trap "kill $pipepid; exit" HUP INT TERM PIPE EXIT
wait $pipepid
