#!/usr/bin/bash

#tray cache location
tray_cache_dir=$($(dirname $0)/init_cache_dir "tray")

tray_cache_file=$tray_cache_dir/state

function get_tray_json {
    if xwininfo -id $(xdotool search --class "stalonetray") | grep -q "IsViewable"; then
        echo -e '{ "hidden":false, "icon":" ", "command": "windowunmap" }'
    else
        echo -e '{ "hidden":true, "icon":" ", "command": "windowmap" }'
    fi
}

get_tray_json > $tray_cache_file
xprop -spy -root _NET_CLIENT_LIST | while read -r; do
    get_tray_json > $tray_cache_file
done &
pipepid=$!

# xprop -spy -root _NET_ACTIVE_WINDOW | while read -r; do

#     xdotool windowunmap $(xdotool search --class "stalonetray")
# done &
# pipepid2=$!

trap "kill $pipepid; kill $pipepid2; exit" HUP INT TERM PIPE EXIT
wait $pipepid
