#!/usr/bin/bash

cd $(dirname $0)

# Installing packages
setup/install_packages

# Installing and configuring oh-my-zsh and friends
setup/install_omz

# Installing and configuring spacemacs
setup/install_emacs

# Installing user configs
setup/install_configs

# Installing systemd service files
setup/install_systemconfigfiles

# Install meslo fonts
setup/install_fonts

# Installing user bin files locally
cp -flav bin $HOME/.local
