#!/usr/bin/bash

cd $(dirname $0)

run_in_seperate_terminal() {
    nohup alacritty --hold -e bash -c "''$@''" >/dev/null &
}

# Installing packages
setup/install_packages

# Installing and configuring oh-my-zsh and friends
setup/install_omz

# Installing and configuring editors
setup/install_editors

# Installing user configs
setup/install_configs

# Installing systemd service files
setup/install_systemconfigfiles

# Installing user bin files locally
cp -flav bin $HOME/.local
