{ pkgs, ... }:
let
  repoJson = builtins.fromJSON (
    builtins.readFile "${pkgs.path}/pkgs/development/mobile/androidenv/repo.json"
  );
  latestVersion =
    package:
    pkgs.lib.last (builtins.sort builtins.lessThan (builtins.attrNames repoJson.packages.${package}));

  androidComposition = pkgs.androidenv.composeAndroidPackages {
    cmdLineToolsVersion = "11.0";
    toolsVersion = "26.1.1";
    platformToolsVersion = latestVersion "platform-tools";

    # Include both 34.0.0 and 36.0.0
    buildToolsVersions = [
      "34.0.0"
      "36.0.0"
    ];

    # Include both API 34 and 36 platforms
    platformVersions = [
      "34"
      "36"
    ];

    # Disable all extras
    includeEmulator = false;
    includeSources = false;
    includeSystemImages = false;
    includeNDK = false;
    useGoogleAPIs = false;
    useGoogleTVAddOns = false;
    includeExtras = [ ];
  };

  androidSdk = androidComposition.androidsdk;
  platformTools = androidComposition.platform-tools;
in
pkgs.mkShell {
  name = "android-shell";
  packages = [
    androidSdk
    platformTools
  ];

  shellHook = ''
    export ANDROID_HOME="${androidSdk}/libexec/android-sdk"
    export GRADLE_OPTS="-Dorg.gradle.project.android.aapt2FromMavenOverride=$ANDROID_HOME/build-tools/36.0.0/aapt2"

    # Create local.properties for Gradle configurations
    cat <<EOF > local.properties
    # This file was automatically generated by nix-shell.
    sdk.dir=$ANDROID_HOME
    EOF

    # Set up local Android directories to not pollute user global folders
    export ANDROID_USER_HOME="$(pwd)/.android"
    mkdir -p "$ANDROID_USER_HOME"

    export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"
    export LD_LIBRARY_PATH="$ANDROID_HOME/build-tools/36.0.0/lib64/:$ANDROID_HOME/build-tools/34.0.0/lib64/:$LD_LIBRARY_PATH"
  '';
}
