#!/bin/bash

## Workspace cache location
workspace_cache_dir=$($(dirname $0)/init_cache_dir "workspace")

workspace_cache_file=$workspace_cache_dir/workspaces

get_workspace_json () {
    wmctrl -d | \
    awk '{ print $1 " " $2 " " $9 }' | \
    jq --raw-input --slurp --compact-output \
    '. |= .[:-1] | split("\n";"") | map(. | split(" ") | { index: .[0], name: .[2], active: (.[1] == "*") })'
}

xprop -spy -root _NET_CURRENT_DESKTOP _NET_NUMBER_OF_DESKTOPS | while read -r; do
    get_workspace_json > $workspace_cache_file
done &

pipepid=$!
trap "kill $pipepid; exit" HUP INT TERM PIPE EXIT
wait $pipepid
