#!/bin/bash

cache_base_dir="/tmp/eww"

supported=("sound" "network" "bluetooth" "weather" "workspace" "tray")

if [[ " ${supported[*]} " =~ " ${1} " ]]; then
    mkdir --parents $cache_base_dir/"$1"
    echo -ne $cache_base_dir/"$1"
else
    mkdir --parents $cache_base_dir
    echo $cache_base_dir
fi
