{
  description = "Unified dev shell with LSP support";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    llm-agents.url = "github:numtide/llm-agents.nix";
  };

  outputs =
    { self, nixpkgs, llm-agents, ... }:
    let
      system = "x86_64-linux";
      
      pkgs = import nixpkgs { 
        inherit system; 
        config = {
          allowUnfree = true; 
          android_sdk.accept_license = true;
        };
      };
      
      llm-agents-pkgs = llm-agents.packages.${system};
      
      # Define the libraries that C-extensions (like numpy) need
      runtimeLibs = with pkgs; [
        # stdenv.cc.cc.lib
      ];
    in
    {
      devShells.${system} = {
        default = let
          # --- Android SDK Setup (Core SDK Only) ---
          repoJson = builtins.fromJSON (builtins.readFile "${pkgs.path}/pkgs/development/mobile/androidenv/repo.json");
          latestVersion = package: pkgs.lib.last (builtins.sort builtins.lessThan (builtins.attrNames repoJson.packages.${package}));

          androidArgs = {
            cmdLineToolsVersion = "11.0";
            toolsVersion = "26.1.1";
            platformToolsVersion = latestVersion "platform-tools";
            
            # Include both 34.0.0 and 36.0.0
            buildToolsVersions = [ "34.0.0" "36.0.0" ];
            
            # Include both API 34 and 36 platforms
            platformVersions = [ "34" "36" ];
            
            # Disable all extras
            includeEmulator = false;
            includeSources = false;
            includeSystemImages = false;
            includeNDK = false;
            useGoogleAPIs = false;
            useGoogleTVAddOns = false;
            includeExtras = [];
          };

          androidComposition = pkgs.androidenv.composeAndroidPackages androidArgs;
          androidSdk = androidComposition.androidsdk;
          platformTools = androidComposition.platform-tools;
        in pkgs.mkShell {
          name = "dev-shell";
          packages = with pkgs; [

            # Numtide LLM Agents
            llm-agents-pkgs.claude-code
            llm-agents-pkgs.claudebox

            # Claude tools (from nixpkgs)
            claude-monitor

            # Go tools
            # go
            # gopls
            # gofumpt
            # gomodifytags
            # gore
            # gotests
            # gotools

            # Spellchecker for doomemacs
            ispell
            hunspell
            hunspellDicts.en_US

            # Markdown preview for doomemacs
            # pandoc

            # Node.js and TypeScript tools
            bun
            # nodejs
            # yarn
            typescript
            typescript-language-server
            vscode-langservers-extracted
            prettier
            eslint
            # corepack

            # Database
            # sqlite

            # Nix
            nil
            nixfmt

            # Supabase
            supabase-cli

            # Python
            # copier
            # black
            # ruff
            # poetry
            # python3
            # ty
            # uv

            # Terraform
            # terraform
            # terraform-providers.dmacvicar_libvirt
            # terraform-ls
            # tfsec

            # k8s
            # kubectl
            # k9s
            
            # Docker
            # lazydocker

            # talos linux
            # talosctl

            # Java
            # jdk17
            # (
            #   let
            #     mavenArgs = lib.functionArgs maven.override;
            #   in
            #   if builtins.hasAttr "jdk" mavenArgs then
            #     maven.override { jdk = jdk17; }
            #   else
            #     maven.override { jdk_headless = jdk17; }
            # )
            # (gradle.override { java = jdk17; })
            # jdt-language-server

            # Android (Core SDK only)
            # androidSdk
            # platformTools
          ];

          # Setup Workspaces and Environment Variables
          shellHook = ''
            # export GOROOT="$\{pkgs.go}/share/go/"
            # export GOPATH=$PWD/.gopath
            # export GOTOOLCHAIN="local";
            
            # Java setup
            # export JAVA_HOME="$\{pkgs.jdk17.home}"

            # Android setup
            # export ANDROID_HOME="$\{androidSdk}/libexec/android-sdk"
            # export GRADLE_OPTS="-Dorg.gradle.project.android.aapt2FromMavenOverride=$ANDROID_HOME/build-tools/36.0.0/aapt2"
            
            # Create local.properties for Gradle configurations
            # cat <<EOF > local.properties
            # # This file was automatically generated by nix-shell.
            # sdk.dir=$ANDROID_HOME
            # EOF

            # Set up local Android directories to not pollute user global folders
            # export ANDROID_USER_HOME=$(pwd)/.android
            # mkdir -p "$ANDROID_USER_HOME"

            # Dynamically build standard paths + C dependencies for both versions
            # export PATH=$GOPATH/bin:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
            # export LD_LIBRARY_PATH="$\{pkgs.lib.makeLibraryPath runtimeLibs}:$ANDROID_HOME/build-tools/36.0.0/lib64/:$ANDROID_HOME/build-tools/34.0.0/lib64/:$LD_LIBRARY_PATH"
          '';
        };
      };
    };
}
