#!/usr/bin/bash

PICOM_CONFIG_LOCATION="$HOME/.config/picom/picom.conf"

cd $(dirname $0)/..

# Evaluating variable to produce actualy string
sed -i -e "s|\$PICOM_CONFIG_LOCATION|$PICOM_CONFIG_LOCATION|g" "systemd/user/picom.service"

# Installing user service file(s)
sudo cp -fav usr /

# Reverting change to service file
sed -i -e "s|$PICOM_CONFIG_LOCATION|\$PICOM_CONFIG_LOCATION|g" "systemd/user/picom.service"
