#!/usr/bin/bash

BACKUP_DIR="$HOME/.config/config.bak"
USER_CONFIG_FILES=(".config" ".zshrc" ".p10k.zsh")

# Ensuring the script is always run relative to the correct directory
cd $(dirname $0)/..

# Checking whether the BACKUP_DIR exists and creating it if it doesn't
if [ ! -d "$BACKUP_DIR" ]
then
    mkdir $BACKUP_DIR
fi

# Cleaning up old config files
find .config -mindepth 1 -maxdepth 1 -type d -exec cp -far $HOME/{} $BACKUP_DIR \; -exec rm -rf $HOME/{} \;

# Copying .config/* files and .rc files
for string in ${USER_CONFIG_FILES[@]}; do
    cp -flav $string $HOME/
done
