#!/usr/bin/bash

PICOM_CONFIG_LOCATION="$HOME/.config/picom/picom.conf"

cd $(dirname $0)/..

# Installing user service file(s) and configs
sudo cp -frv usr /

# Installing system level/global configs
sudo cp -frv etc /

# Evaluating variable to produce actualy string
sudo sed -i -e "s|\$PICOM_CONFIG_LOCATION|$PICOM_CONFIG_LOCATION|g" "/usr/lib/systemd/user/picom.service"
