#!/usr/bin/bash

url_base="https://github.com/romkatv/powerlevel10k-media/raw/master"
fonts_dir="/usr/share/fonts/"
tmp_dl_dir="/tmp/MesloLGS-Powerlevel10k"

urls=(
    "$url_base/MesloLGS%20NF%20Regular.ttf"
    "$url_base/MesloLGS%20NF%20Italic.ttf"
    "$url_base/MesloLGS%20NF%20Bold%20Italic.ttf"
    "$url_base/MesloLGS%20NF%20Bold.ttf"
)

mkdir $tmp_dl_dir

curl --parallel --parallel-max 8 --location --output-dir $tmp_dl_dir --remote-name-all ${urls[@]}

# Remove urlencodings
for f in $tmp_dl_dir/*.ttf; do
    mv "$f" "$(echo -e "$(echo "$f" | sed 's/+/ /g;s/%\(..\)/\\x\1/g;s/\\x\(2[Ff]\)/%\1/g')")"
done

sudo mv $tmp_dl_dir $fonts_dir

fc-cache -f
