#!/usr/bin/bash

git clone --depth 1 https://github.com/doomemacs/doomemacs "${HOME}"/.emacs.d
run_in_seperate_terminal '"${HOME}"/.emacs.d/bin/doom install'

curl -sLf https://spacevim.org/install.sh | bash -s -- --install neovim

sudo pacman -Syu bash-language-server clang lua-language-server pyright rust-analyzer typescript-language-server vscode-css-languageserver vscode-html-languageserver vscode-json-languageserver
yay -Syu jdtls omnisharp-roslyn-bin

mkdir --parents "${HOME}"/.emacs.d/.local/etc/lsp
cp --recursive --symbolic-link /usr/share/java/jdtls ~/.emacs.d/.local/etc/lsp/eclipse.jdt.ls
